//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeAccessServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfficeEmployee
    {
        public int empid { get; set; }
        public string empfirstName { get; set; }
        public string empLastName { get; set; }
        public Nullable<int> empSalary { get; set; }
    }
}
